=== dita-semia/XsltConref/samples/advanced-keyref/database-table/01-key-definitions/Table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs	= "http://www.w3.org/2001/XMLSchema"
	xmlns:cba	= "http://www.dita-semia.org/conbat"
	xmlns:ikd	= "http://www.dita-semia.org/implicit-keydef"
	elementFormDefault="qualified">
	
	
	<xs:import namespace="http://www.dita-semia.org/conbat" 			schemaLocation="urn:dita-semia:conbat:schema:conbat-attr.xsd"/>
	<xs:import namespace="http://www.dita-semia.org/implicit-keydef" 	schemaLocation="urn:dita-semia:advanced-keyref:schema:ikd-attr.xsd"/>


	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:NCName">
								<xs:attribute name="class" 			fixed="+ topic/title "/>
								<xs:attribute ref="cba:prefix" 		fixed="Table: "/>
								<xs:attribute ref="ikd:key-type" 	fixed="db-table"/>
								<xs:attribute ref="ikd:root" 		fixed="parent::table"/>
								<xs:attribute ref="ikd:namespace" 	fixed="def/properties/schema"/>
								<xs:attribute ref="ikd:desc" 		fixed="desc"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="desc">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="class" fixed="+ topic/shortdesc "/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="def">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="columns">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="column" type="columnType"/>
									</xs:sequence>
									<xs:attribute name="class" fixed="+ topic/simpletable "/>
									<xs:attribute name="relcolwidth" default="1.0* 1.0* 2.0*"/>
									<xs:attribute ref="cba:header" 	fixed="Name|Type|Description"/>	
								</xs:complexType>
							</xs:element>
							<xs:element name="properties" type="propertiesType"/>
						</xs:sequence>
						<xs:attribute name="class" fixed="- topic/body "/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="class" 		fixed="+ topic/topic "/>
			<xs:attribute name="domains" 	fixed="(topic hi-d) (topic pr-d) (topic reference) (topic sw-d)"/>
			<xs:attribute name="id"			fixed="DITA-dummy-id"/>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="columnType">
		<xs:sequence>
			<xs:element name="name">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:NCName">
							<xs:attribute name="class" 			fixed="+ topic/stentry "/>
							<xs:attribute ref="ikd:key-type"	fixed="db-column"/>
							<xs:attribute ref="ikd:root"		fixed="parent::column"/>
							<xs:attribute ref="ikd:namespace "	fixed="ikd:ancestor-path('db-table')"/>
							<xs:attribute ref="ikd:desc"		fixed="concat(desc, ' (type: ', def/type, ')')"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="def" type="columnDefType"/>
			<xs:element name="desc">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="class" fixed="+ topic/stentry "/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" fixed="+ topic/strow "/>
		<xs:attribute name="id"/>
	</xs:complexType>
	
	
	<xs:complexType name="columnDefType">
		<xs:sequence>
			<xs:element name="type">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:token">
							<xs:attribute name="class" 			fixed="+ topic/ph pr-d/codeph "/>
							<xs:attribute ref="cba:flags"		fixed="csli"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="not-null" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="class" 			fixed="+ topic/ph "/>
					<xs:attribute ref="cba:content" 	fixed="Not-Null"/>
					<xs:attribute ref="cba:flags"		fixed="csli"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" fixed="+ topic/stentry "/>
	</xs:complexType>


	<xs:complexType name="propertiesType">
		<xs:sequence>
			<xs:element name="schema">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:NCName">
							<xs:attribute name="class" 			fixed="+ topic/dd "/>
							<xs:attribute ref="cba:flags" 		fixed="code"/>
							<xs:attribute ref="cba:dt" 			fixed="Schema"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="log-table">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:NCName">
							<xs:attribute name="method">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="by trigger"/>
										<xs:enumeration value="explicit"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="class" 			fixed="+ topic/dd "/>
							<xs:attribute ref="cba:dt" 			fixed="Log Table"/>
							<xs:attribute ref="cba:popup-edit" 	fixed="method"/>
							<xs:attribute ref="cba:flags" 		fixed="code pe-braced"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" 			fixed="+ topic/dl "/>
		<xs:attribute name="outputclass" 	fixed="header-table"/>
		<xs:attribute ref="cba:title" 		fixed="Properties of Table {ancestor::table/name}"/>
	</xs:complexType>
	
	
</xs:schema>

=== dita-semia/XsltConref/samples/advanced-keyref/database-table/01-key-definitions/table-person.xml
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Table.xsd">
	<name>Person</name>
	<desc>List of all people.</desc>
	<def>
		<columns>
			<column id="ihv_34b_wy">
				<name>PersonId</name>
				<def>
					<type>int</type>
					<not-null/>
				</def>
				<desc>Unique ID</desc>
			</column>
			<column id="ntz_34b_wy">
				<name>Name</name>
				<def>
					<type>varchar(255)</type>
					<not-null/>
				</def>
				<desc>The full name of the person</desc>
			</column>
			<column id="l51_j4b_wy">
				<name>EMail</name>
				<def>
					<type>varchar(255)</type>
				</def>
				<desc>The email address</desc>
			</column>
		</columns>
		<properties>
			<schema>DB1</schema>
			<log-table method="by trigger">PersonLog</log-table>
		</properties>
	</def>
</table>
